version: "3.7"
services:

  db:
    image: mysql/mysql-server
    container_name: db_docker_symfony_fpm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '!password_here!'
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: '!password_here!'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3317:3306" #outside:inside docker container from-within

  php:
    build: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app/api:/var/www/symfony_docker
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app/api:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db