controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login:
    path: /api/login
    controller: App\Controller\ApiLoginController::login

register:
    path: /api/register
    controller: App\Controller\RegistrationController::register